spring.application.name=car-booking-service
server.port=8080
spring.jpa.open-in-view=false
spring.profiles.default=local
credit-card-validation.base-url=http://localhost:9090/host/credit-card-payment-api
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.consumer.group-id=car-booking-service
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.properties.spring.deserializer.key.delegate.class=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=com.velocitymotors.carbooking.model.payment
spring.kafka.consumer.properties.spring.json.value.default.type=com.velocitymotors.carbooking.model.payment.BankTransferPaymentEventRequest
bank-transfer.payment-events-topic=bank-transfer-payment-events
booking.cancellation.fixed-delay-ms=60000
#booking.cancellation.minutes=2880
booking.cancellation.minutes=5
booking.cancellation.batch-size=100
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=when_authorized
management.tracing.enabled=true
management.tracing.sampling.probability=1.0
management.otlp.tracing.endpoint=http://localhost:4318/v1/traces
spring.application.instance-id=${spring.application.name}:${random.uuid}